FROM quay.io/assemblyline/buildpack_deps:14.04

ENV NODE_VERSION <%= version %>
ENV NPM_VERSION <%= NPM_VERSION %>
COPY SHASUMS256.txt /SHASUMS256.txt

RUN curl -SLO "http://nodejs.org/dist/v<%= version %>/node-v<%= version %>-linux-x64.tar.gz" \
      && cat SHASUMS256.txt | sha256sum -c - \
      && tar -xzf "node-v<%= version %>-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
      && rm "node-v<%= version %>-linux-x64.tar.gz" SHASUMS256.txt \
      && npm install -g npm@<%= NPM_VERSION %> \
      && npm cache clear
