FROM quay.io/assemblyline/buildpack_deps

ENV NODE_VERSION <%= version %>
COPY SHASUMS256.txt /SHASUMS256.txt

RUN curl -SLO "http://nodejs.org/dist/v<%= version %>/node-v<%= version %>-linux-x64.tar.gz" \
      && cat SHASUMS256.txt | sha256sum -c - \
      && tar -xzf "node-v<%= version %>-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
      && rm "node-v<%= version %>-linux-x64.tar.gz" SHASUMS256.txt
