FROM quay.io/assemblyline/buildpack_deps:14.04

ENV NODE_VERSION <%= data['version'] %>
ENV NPM_VERSION <%= data['npm_version'] %>
COPY SHASUMS256.txt /SHASUMS256.txt

RUN curl -SLO "http://nodejs.org/dist/v<%= data['version'] %>/node-v<%= data['version'] %>-linux-x64.tar.gz" \
      && cat SHASUMS256.txt | sha256sum -c - \
      && tar -xzf "node-v<%= data['version'] %>-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
      && rm "node-v<%= data['version'] %>-linux-x64.tar.gz" SHASUMS256.txt \
      && npm install -g npm@<%= data['npm_version'] %> \
      && npm cache clear
