FROM quay.io/assemblyline/buildpack_deps:14.04

ENV NODE_VERSION <%= data['version'] %>
ENV NPM_VERSION <%= data['npm_version'] %>

RUN curl -SLO "http://nodejs.org/dist/v<%= data['version'] %>/node-v<%= data['version'] %>-linux-x64.tar.gz" \
      && echo "<%= data['checksum'] %> node-v<%= data['version'] %>-linux-x64.tar.gz" | sha256sum -c - \
      && tar -xzf "node-v<%= data['version'] %>-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
      && npm install -g npm@<%= data['npm_version'] %> \
      && npm cache clear --force
